### ISSUE TITLE
Allow using AMIs built for architectures other than amd64

### ISSUE THREAD

**Issue by ldx** [elotl/kip#202]
Right now kip can only use one AMI specified via `bootImageSpec` in provider.yaml.

However, AMIs are specific to the OS and CPU architecture. To support other architectures and OSes (ARM, mac1, etc) we need to be able to specify a boot image filter for each.

**Comment by hidalgopl** [comment]
@ldx @jrroman @henryprecheur What you guys think of having something really generic, such as:
```yaml
bootImageSpec:
    amis:
      - familyRegex: "mac.*"
        owners: 689494258501
        filters: name=elotl-kip-*
     - familyRegex: "*" # default
       owners: 689494258501
       filters: name=elotl-kip-*
```

**Comment by jrroman** [comment]
@hidalgopl so the issue i see with this is it will break reverse compatibility with previous releases of kip. We could potentially add this for additional ami fields while keeping the base of owner and filter.  This is the way i have been testing currently:

```yaml
 16   bootImageSpec:
 17     owners: 689494258501
 18     filters: name=elotl-kip-*
 19     macfilters: name=elotl-kipmac-*
 20     armfilters: name=elotl-kiparm-*
```

**Comment by hidalgopl** [comment]
@jrroman You're right, I haven't thought about it. We can keep backwards compatibility by keeping what I proposed under new key:
 ```yaml
 bootImageSpec:
      owners: 689494258501
      filters: name=elotl-kip-*
      overrideAMI:
       - familyRegex: "mac.*"
         owners: 689494258501
         filters: name=elotl-kip-mac*
      - familyRegex: "*" # default
        owners: 689494258501
        filters: name=elotl-kip-*
```
Big question is how flexible this feature needs to be. And whether we want to have different AMI for different arch, or different AMI for different instance type familiy.
For our current needs keys you added are fully sufficient. However, if ever we want to be able to have different AMI for different instance type/family, introducing changes would be tricky if we already have feature that chooses AMI based on arch.
