### ISSUE TITLE
GCE Instances are not terminated fully

### ISSUE THREAD

**Issue by justnoise** [elotl/kip#76]
This one is strange: It seems like we can tell GCE to terminate an instance, we get an OK back from the API and then the instance isn't terminated.  The node inside kip is stuck in the "terminating" state

```yaml
apiVersion: v1
kind: Node
metadata:
  creationTimestamp: "2020-05-06T22:17:27.781711586Z"
  labels: {}
  name: d6385a15-5730-4d39-a8a2-f890344cca41
  namespace: default
  uid: b1e223a1-4742-4bf2-bbf5-89fa8cd1ba2d
spec:
  bootImage: https://www.googleapis.com/compute/v1/projects/ubuntu-os-cloud/global/images/ubuntu-1804-bionic-v20200414
  instanceType: e2-highmem-4
  placement: {}
  resources:
    cpu: "4.00"
    memory: 20.00Gi
    sustainedCPU: false
    volumeSize: 10G
  spot: false
status:
  addresses: null
  boundPodName: ""
  instanceID: ""
  phase: Terminating
```

I'm unsure if the most recent work to check the status of operations will help with ensuring the nodes are terminated.  Might need to handle more cases in the Garbage Controller.
